config/routes.rb
Instock::Application.routes.draw do
  root :to                   => 'home#index'

  match 'contact'            => 'home#contact'
  match 'about'              => 'home#about'
  match 'preferences'        => 'home#preferences'
  match 'support'            => 'home#support'
  match 'dashboard'          => 'home#dashboard'

  match 'login'              => 'login#index'
  match 'login/authenticate' => 'login#authenticate'
  match 'login/finalize'     => 'login#finalize'
  match 'login/logout'       => 'login#logout'

  match 'client_shop_management/record_shop'  => 'client_shop_management#record_shop'

  match 'ajax/receiving_items'  => 'ajax#receiving_items'
  match 'ajax/stock_adjustment_items'  => 'ajax#stock_adjustment_items'
  match 'ajax/vendor_products'  => 'ajax#vendor_products'
  match 'ajax/methods'  => 'ajax#methods'
  match 'ajax/collection_products'  => 'ajax#collection_products'

  resources :stock_audits do
    resources :stock_audit_items, :only => :none
  end

  resources :receivings do |receivings|
    resources :receiving_items, :only => :none
  end

  resources :stock_adjustments do
    resources :stock_adjustment_items, :only => :none
  end

  resources :client_shops

  #Admin
  #map.admin_logout "admin_logout", :controller => "admin_sessions", :action => "destroy"
  #Resources
  #map.resource :account, :controller => "admins"
  #map.resources :admins 
  #map.resource :admin_session
    #map.root :controller => "admin_session_sessions", :action => "new"
end

app/models/client_shop.rb
class ClientShop < ActiveRecord::Base
end

app/controllers/client_shops_controller.rb
class ClientShopsController < ApplicationController
  before_filter :require_admin
  layout 'client_shops'
  
  # GET /client_shops
  # GET /client_shops.xml
  def index
    @client_shops = ClientShop.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @client_shops }
    end
  end

  # GET /client_shops/1
  # GET /client_shops/1.xml
  def show
    @client_shop = ClientShop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @client_shop }
    end
  end

  # GET /client_shops/new
  # GET /client_shops/new.xml
  def new
    @client_shop = ClientShop.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @client_shop }
    end
  end

  # GET /client_shops/1/edit
  def edit
    @client_shop = ClientShop.find(params[:id])
  end

  # POST /client_shops
  # POST /client_shops.xml
  def create
    @client_shop = ClientShop.new(params[:client_shop])

    respond_to do |format|
      if @client_shop.save
        flash[:notice] = 'ClientShop was successfully created.'
        format.html { redirect_to(@client_shop) }
        format.xml  { render :xml => @client_shop, :status => :created, :location => @client_shop }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @client_shop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /client_shops/1
  # PUT /client_shops/1.xml
  def update
    @client_shop = ClientShop.find(params[:id])

    respond_to do |format|
      if @client_shop.update_attributes(params[:client_shop])
        flash[:notice] = 'ClientShop was successfully updated.'
        format.html { redirect_to(@client_shop) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @client_shop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /client_shops/1
  # DELETE /client_shops/1.xml
  def destroy
    @client_shop = ClientShop.find(params[:id])
    @client_shop.destroy

    respond_to do |format|
      format.html { redirect_to(client_shops_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/client_shops/edit.html.erb
<h1>Editing client_shop</h1>

<% form_for(@client_shop) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :domain %><br />
    <%= f.text_field :domain %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :shopify_store_id %><br />
    <%= f.text_field :shopify_store_id %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :shop-owner %><br />
    <%= f.text_field :shop-owner %>
  </p>
  <p>
    <%= f.label :active-subscription-id %><br />
    <%= f.text_field :active-subscription-id %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @client_shop %> |
<%= link_to 'Back', client_shops_path %>

app/views/client_shops/index.html.erb
<h1>Listing Client Shops</h1>

<table>
  <tr>
    <th>Domain</th>
    <th>Name</th>
    <th>Shopify store</th>
    <th>Email</th>
    <th>Name</th>
    <th>Shop-owner</th>
    <th>Active-subscription-id</th>
  </tr>

<% @client_shops.each do |client_shop| %>
  <tr>
    <td><%= link_to client_shop.domain, "http://#{client_shop.domain}", {:target => "_blank"}  %></td>
    <td><%=h client_shop.name %></td>
    <td><%=h client_shop.shopify_store_id %></td>
    <td><%=h client_shop.email %></td>
    <td><%=h client_shop.name %></td>
    <td><%=h client_shop.shop_owner %></td>
    <td><%=h client_shop.active_subscription_id %></td>
    <td><%= link_to 'Show', client_shop %></td>
    <td><%= link_to 'Edit', edit_client_shop_path(client_shop) %></td>
    <td><%= link_to 'Destroy', client_shop, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/client_shops/new.html.erb
<h1>New client_shop</h1>

<% form_for(@client_shop) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :domain %><br />
    <%= f.text_field :domain %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :shopify_store_id %><br />
    <%= f.text_field :shopify_store_id %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :shop-owner %><br />
    <%= f.text_field :shop-owner %>
  </p>
  <p>
    <%= f.label :active-subscription-id %><br />
    <%= f.text_field :active-subscription-id %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', client_shops_path %>

app/views/client_shops/show.html.erb
<p>
  <b>Domain:</b>
  <%=h @client_shop.domain %>
</p>

<p>
  <b>Name:</b>
  <%=h @client_shop.name %>
</p>

<p>
  <b>Shopify store:</b>
  <%=h @client_shop.shopify_store_id %>
</p>

<p>
  <b>Email:</b>
  <%=h @client_shop.email %>
</p>

<p>
  <b>Name:</b>
  <%=h @client_shop.name %>
</p>

<p>
  <b>Shop-owner:</b>
  <%=h @client_shop.shop_owner %>
</p>

<p>
  <b>Active-subscription-id:</b>
  <%=h @client_shop.active_subscription_id %>
</p>


<%= link_to 'Edit', edit_client_shop_path(@client_shop) %> |
<%= link_to 'Back', client_shops_path %>