config/routes.rb
Instock::Application.routes.draw do
  root :to                   => 'home#index'

  match 'contact'            => 'home#contact'
  match 'about'              => 'home#about'
  match 'preferences'        => 'home#preferences'
  match 'support'            => 'home#support'
  match 'dashboard'          => 'home#dashboard'

  match 'login'              => 'login#index'
  match 'login/authenticate' => 'login#authenticate'
  match 'login/finalize'     => 'login#finalize'
  match 'login/logout'       => 'login#logout'

  match 'client_shop_management/record_shop'  => 'client_shop_management#record_shop'

  match 'ajax/receiving_items'  => 'ajax#receiving_items'
  match 'ajax/stock_adjustment_items'  => 'ajax#stock_adjustment_items'
  match 'ajax/vendor_products'  => 'ajax#vendor_products'
  match 'ajax/methods'  => 'ajax#methods'
  match 'ajax/collection_products'  => 'ajax#collection_products'

  resources :stock_audits do
    resources :stock_audit_items, :only => :none
  end

  resources :receivings do |receivings|
    resources :receiving_items, :only => :none
  end

  resources :stock_adjustments do
    resources :stock_adjustment_items, :only => :none
  end

  resources :client_shops

  #Admin
  #map.admin_logout "admin_logout", :controller => "admin_sessions", :action => "destroy"
  #Resources
  #map.resource :account, :controller => "admins"
  #map.resources :admins 
  #map.resource :admin_session
    #map.root :controller => "admin_session_sessions", :action => "new"
end

app/models/stock_adjustment.rb
class StockAdjustment < ActiveRecord::Base
  has_many :stock_adjustment_items
  accepts_nested_attributes_for  :stock_adjustment_items
  
  # Validations
  validates_presence_of(:created_by, :message => "'Staff Member' can't be blank.")
  validates_presence_of(:shopify_store_id)
  validates_presence_of(:reason)
end

app/controllers/stock_adjustments_controller.rb
class StockAdjustmentsController < ApplicationController
  around_filter :shopify_session

  def index
    @stock_adjustments = StockAdjustment.find(:all, :conditions => ["shopify_store_id = ?", current_shop.shop.id])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stock_adjustments }
    end
  end

  def show
    begin
    @stock_adjustment = StockAdjustment.find(params[:id], :conditions => ["shopify_store_id = ?", current_shop.shop.id])
    rescue ActiveRecord::RecordNotFound
      logger.error("Attempt to access a stock adjustment that doesnt exist (#{params[:id]}) for the current shop (#{current_shop.domain}).")
      flash[:error] = "Could not find that stock adjustment!"
      redirect_to(:action => 'index')
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @stock_adjustment }
      end
    end #begin
  end

  def new
    @vendor_names = ShopifyAPI::Product.find(:all).map{|product| product.vendor}.uniq
    @stock_adjustment = StockAdjustment.new
    

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @stock_adjustment }
    end
  end

  
  #def edit
  #  @stock_adjustment = StockAdjustment.find(params[:id])
  #end

  def create
    @stock_adjustment = StockAdjustment.new(params[:stock_adjustment])
    @stock_adjustment.shopify_store_id = current_shop.shop.id

    respond_to do |format|
      if @stock_adjustment.save
        flash[:notice] = "Stock Adjustment was successfully created."
        format.html { redirect_to(@stock_adjustment) }
        format.xml  { render :xml => @stock_adjustment, :status => :created, :location => @stock_adjustment }
      else
        flash[:error] = "Could not save this Stock Adjustment. Please try again."
        format.html { render :action => "create" }
        format.xml  { render :xml => @stock_adjustment.errors, :status => :unprocessable_entity }
      end
    end
  end

  
  #def update
  #  @stock_adjustment = StockAdjustment.find(params[:id])
  #
  #  respond_to do |format|
  #    if @stock_adjustment.update_attributes(params[:stock_adjustment])
  #      flash[:notice] = 'StockAdjustment was successfully updated.'
  #      format.html { redirect_to(@stock_adjustment) }
  #      format.xml  { head :ok }
  #    else
  #      format.html { render :action => "edit" }
  #      format.xml  { render :xml => @stock_adjustment.errors, :status => :unprocessable_entity }
  #    end
  #  end
  #end

  def destroy
    @stock_adjustment = StockAdjustment.find(params[:id])
    @stock_adjustment.destroy

    respond_to do |format|
      format.html { redirect_to(stock_adjustments_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/stock_adjustments/create.html.erb
<% content_for(:custom_js, javascript_include_tag('variant_select')) %>
<h1 class="blue">Enter Receiving Data</h1>
<div id="stockAdjustmentForm">
  <div class="box">
    <%= render(:file => "ajax/stock_adjustment_items.html.erb")%>
  </div>
</div>

app/views/stock_adjustments/edit.html.erb
<h1>Editing stock_adjustment</h1>

<% form_for(@stock_adjustment) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :shopify_store_id %><br />
    <%= f.text_field :shopify_store_id %>
  </p>
  <p>
    <%= f.label :reason %><br />
    <%= f.text_field :reason %>
  </p>
  <p>
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </p>
  <p>
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </p>
  <p>
    <%= f.label :updated_at %><br />
    <%= f.datetime_select :updated_at %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @stock_adjustment %> |
<%= link_to 'Back', stock_adjustments_path %>

app/views/stock_adjustments/index.html.erb
<h1 class="blue">Stock Adjustments</h1>
<% if @stock_adjustments.blank? %>
  <div class="box wrapper">
    <em class="note">You have not done any <strong>stock adjustments</strong> yet.</em>
  </div>
<% else %>
  <div class="box wrapper">
  <table>
    <thead>
      <tr><td>Date</td><td>Reason</td><td>Employee</td><td colspan="2">&nbsp;</td></tr>
    </thead>
    <tbody>
    <% @stock_adjustments.each do |stock_adjustment| %>
      <tr>
        <td><%= link_to(stock_adjustment.created_at , {:action => 'show', :id => stock_adjustment.id}) %></td>
        <td><%=h stock_adjustment.reason %></td>
        <td><%=h stock_adjustment.created_by %></td>
        <td><%= link_to 'X', stock_adjustment, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </div>
<% end #if %>
<p><%= link_to("Add Stock Adjustment", {:action => 'new', :controller => 'stock_adjustments'}, :method => :get) %></p>

app/views/stock_adjustments/new.html.erb
<h1 class="blue">Enter Stock Adjustment Data</h1>

<%= form_tag "javascript:void(0)", {:id => :method_select} do %>
  <div class="box">
    <h2 class="blue">Step One</h2>
    <div class="wrapper">
      <span class="highlight">Choose how you want to make this stock adjustment: </span>
      <br /> <br />
      <%= select_tag :method, options_for_select(
        {"Select a Method" => 'choose', "By Vendors" => 'vendors', "By Collections" => 'collections'}, 
        {:selected => 'choose', :disabled => 'choose'}
      )%>
      <br />
    </div>
  </div>
<% end %>

<%= form_tag "/ajax/stock_adjustment_items", :remote => true, :id => "stock_adjustment_items" do %>
  <div class="box">
    <h2 class="blue">Step Two</h2>
    <table>
        <tr>
          <td valign="top">
            <label for="vendors">From:</label>
          </td>
          <td id="selector" class="firstCol">
            <span class="highlight">Please select a method for choosing products from above.</span>
          </td>
          <td valign="top">
            <label for="product_variants">Variants:</label>
          </td>
          <td>
            <div id="productVariants"></div>
          </td>
        </tr>
    </table>
  </div>
  <br />
  <%= submit_tag("Use Checked Variants", :onclick => "start_spinner($('#stockAdjustmentForm .box .wrapper'))")%>
<% end %>
<br />
<div id="stockAdjustmentForm">
  <div class="box">
    <h2 class="blue">Step Three</h2>
    <div class="wrapper" id="stepThree">
    <span class="highlight">Select a vendor and at least one variant</span>
    </div>
  </div>
</div>

app/views/stock_adjustments/show.html.erb
<h1 class="blue">Stock Adjustment</h1>
<h2>Reason: <span class="highlight"><%= @stock_adjustment.reason %></span></h2>
<h2>Date: <span class="highlight"><%= @stock_adjustment.created_at %></span></h2>
<h2>Staff Member: <span class="highlight"><%= @stock_adjustment.created_by %></span></h2>

<div class="box">
    <h2>Adjusted Stock:</h2>
    <table>
      <thead>
        <% 
          reason_heading = case(@stock_adjustment.reason)
          when "Defective"
			"Defectives"
          when "Donation"
			"Donated"
          when "Found"
			"Found"
          else
            "Adjusted"
          end #case
        %>
        <tr><td>Product Variant</td><td>Sku</td><td><%= reason_heading %></td></tr>
      </thead>
      <tbody>
        <% @stock_adjustment.stock_adjustment_items.each do |si| %>
            <tr>
                <td><%= si.title %></td>
                <td><%= si.sku || "(no sku?)" %></td>
                <td><%= si.count %></td>
            </tr>
        <% end %>
        <tbody>
    </table>
</div>

<%= link_to("All Stock Adjustments", {:action => 'index'}, :method => :get) %>