config/routes.rb
Instock::Application.routes.draw do
  root :to                   => 'home#index'

  match 'contact'            => 'home#contact'
  match 'about'              => 'home#about'
  match 'preferences'        => 'home#preferences'
  match 'support'            => 'home#support'
  match 'dashboard'          => 'home#dashboard'

  match 'login'              => 'login#index'
  match 'login/authenticate' => 'login#authenticate'
  match 'login/finalize'     => 'login#finalize'
  match 'login/logout'       => 'login#logout'

  match 'client_shop_management/record_shop'  => 'client_shop_management#record_shop'

  match 'ajax/receiving_items'  => 'ajax#receiving_items'
  match 'ajax/stock_adjustment_items'  => 'ajax#stock_adjustment_items'
  match 'ajax/vendor_products'  => 'ajax#vendor_products'
  match 'ajax/methods'  => 'ajax#methods'
  match 'ajax/collection_products'  => 'ajax#collection_products'

  resources :stock_audits do
    resources :stock_audit_items, :only => :none
  end

  resources :receivings do |receivings|
    resources :receiving_items, :only => :none
  end

  resources :stock_adjustments do
    resources :stock_adjustment_items, :only => :none
  end

  resources :client_shops

  #Admin
  #map.admin_logout "admin_logout", :controller => "admin_sessions", :action => "destroy"
  #Resources
  #map.resource :account, :controller => "admins"
  #map.resources :admins 
  #map.resource :admin_session
    #map.root :controller => "admin_session_sessions", :action => "new"
end

app/models/stock_audit.rb
class StockAudit < ActiveRecord::Base
  has_many :stock_audit_items
  accepts_nested_attributes_for :stock_audit_items
  
  validates_presence_of :created_by, :message => "cannot be empty."
  validates_presence_of :shopify_store_id
end

app/controllers/stock_audits_controller.rb
class StockAuditsController < ApplicationController
  around_filter :shopify_session
  protect_from_forgery
  layout "application"
  
  @@shopify_product_limit = 250.0
  
  def index
    @audits = StockAudit.find :all, :conditions => ["shopify_store_id = ? AND deleted = ?", current_shop.shop.id, false]

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @audits }
    end
  end
  
  def new
    # Set up the needed variables
    @audit = StockAudit.new
    fulfillments = []
    @products = {}
    
    # Gather the data from Shopify
    # Products are limited, deal with it.
    product_count = ShopifyAPI::Product.count
    page_count = (product_count / @@shopify_product_limit).ceil
    products = []
    page_count.times do |page|
      # Not only can I not get *all* products with find(:all) but their page indexing starts at 1 instead of 0 :-(
      products += ShopifyAPI::Product.find(:all, :params => {:limit => @@shopify_product_limit, :page => page + 1}, :sort => :title)
    end
    
    orders = ShopifyAPI::Order.find(:all, :params => { :status => "open", :fulfillment_status => "unshipped OR partial"})
    orders.each do |order|
      ShopifyAPI::Fulfillment.find(:all, :params => { :order_id => order.id } ).each do |f|
        unless f.nil?
          fulfillments << f
        end
      end
    end

    # Build all the StockAuditItems with data and insert them into @audit
    products.each do |product|
      product.variants.each do |variant|
        item = StockAuditItem.new
        item.vendor = product.vendor
        item.product_id = product.id
        item.variant_id = variant.id
        item.title = variant.title
        item.product_title = product.title
        item.sku = variant.sku ? variant.sku : "none"
        item.shopify_count = variant.inventory_quantity
        item.pending_count = orders.map{ |order| order.line_items.select{ |i| i.variant_id == item.variant_id }.map{|i| i.quantity }}.flatten.inject(0) {|sum,element| sum + element }
        item.pending_count -= fulfillments.map { |fulfillment| fulfillment.line_items.select { |i| i.variant_id == item.variant_id }.map { |i| i.quantity }}.flatten.inject(0) { |sum, element| sum + element }
        item.expected_count = item.shopify_count + item.pending_count
        @audit.stock_audit_items << item
      end
    end

    @vendors = @audit.stock_audit_items.map{ |item| item.vendor}.uniq.sort{ |a,b| a.casecmp(b)}
    @vendors.each do |vendor|
      @products[vendor] = @audit.stock_audit_items.select{ |item| item.vendor == vendor }.map{ |item| [item.product_title, item.product_id] }.uniq.sort{ |a, b| a[0].casecmp(b[0]) }
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @audit }
    end
  end
  
  def create
    @audit = StockAudit.new(params[:stock_audit])

    respond_to do |format|
      if @audit.save
        flash[:notice] = 'Audit was successfully created.'
        format.html { redirect_to @audit }
        format.xml  { render :xml => @audit, :status => :created, :location => @audit }
      else
        @products = {}
        @vendors = @audit.stock_audit_items.map{ |item| item.vendor}.uniq.sort{ |a,b| a.casecmp(b)}
        @vendors.each do |vendor|
          @products[vendor] = @audit.stock_audit_items.select{ |item| item.vendor == vendor }.map{ |item| [item.product_title, item.product_id] }.uniq.sort{ |a, b| a[0].casecmp(b[0]) }
        end

        format.html { render :action => "new" }
        format.xml  { render :xml => @audit.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def show
    @audit = StockAudit.find(params[:id], :conditions => ["shopify_store_id = ?", current_shop.shop.id], :include => :stock_audit_items)
    @products = {}
    @vendors = @audit.stock_audit_items.map{ |item| item.vendor}.uniq.sort{ |a,b| a.casecmp(b)}
    @vendors.each do |vendor|
      @products[vendor] = @audit.stock_audit_items.select{ |item| item.vendor == vendor }.map{ |item| [item.product_title, item.product_id] }.uniq.sort{ |a, b| a[0].casecmp(b[0]) }
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @audit }
    end
  end

  # Disable editing of stock audits
  #def edit
  #  @audit = StockAudit.find(params[:id], :conditions => ["shopify_store_id = ?", current_shop.shop.id], :include => :stock_audit_items )
  #end
  
  #def update
  #  @audit = StockAudit.find(params[:id], :conditions => ["shopify_store_id = ?", current_shop.shop.id])

  #  respond_to do |format|
  #    if @audit.update_attributes(params[:audit])
  #      flash[:notice] = 'StockAudit was successfully updated.'
  #      format.html { redirect_to(@audit) }
  #      format.xml  { head :ok }
  #    else
  #      format.html { render :action => "edit" }
  #      format.xml  { render :xml => @audit.errors, :status => :unprocessable_entity }
  #    end
  #  end
  #end

  def destroy
    @audit = StockAudit.find(params[:id], :conditions => ["shopify_store_id = ?", current_shop.shop.id])
    # Don't destroy the object. Set it to deleted.
    #@audit.destroy
    @audit.deleted = true
    @audit.save

    respond_to do |format|
      format.html { redirect_to :action => "index" }
      format.xml  { head :ok }
    end
  end
end

app/views/stock_audits/index.html.erb
<h1 class="blue">Stock Audits</h1>
<% if @audits.blank? %>
<div class="box wrapper">
  <em class="note">You have not done any stock audits yet.</em>
</div>
<% else %>

<div class="box wrapper">
  <table>
    <thead>
      <tr><td>Date</td><td>Staff Member</td><td colspan="2">&nbsp;</td></tr>
    </thead>
    <tbody>
      <% @audits.each do |audit| %>
        <tr>
          <td><%= link_to(audit.created_at, :action => 'show', :id => audit.id) %></td>
          <td><%=h audit.created_by %></td>
          <td><%= link_to("X", {:action => 'destroy', :id => audit.id}, :confirm => "Are you sure?", :method => :delete) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<% end %>

<p><%= link_to "Create new stock audit", url_for(:action => :new) %></p>

app/views/stock_audits/new.html.erb
<h1 class="blue">Enter Stock Audit</h1>
  <%= error_messages_for :audit %>
  <table>
    <thead>
      <tr>
        <td>Variant</td>
        <td>Shopify Count</td>
        <td>Alocated To Orders</td>
        <td>Expected On Hand</td>
        <td>Actual Count</td>
        <td>Difference</td>
      </tr>
    </thead>
    <tbody>
      <%= form_for @audit, :url => stock_audits_path(@audit), :validate => true do |audit| %>
        <% even_or_odd_vendor = 1 %>
        <% @vendors.each do |vendor| %>
          <% even_or_odd_vendor = (even_or_odd_vendor - 1).abs %>
            <% @products[vendor].each do |product| %>
              <tr>
                <td colspan="6" class="vendor<%= even_or_odd_vendor %>">
                  <%= if not current_shop.nil?
                        link_to product[0], "http://#{current_shop.domain}/admin/products/#{product[1]}"
                      end %>
                  (<%= vendor %>)
                </td>
              </tr>
              <% even_or_odd_variant = 1 %>
              <% @audit.stock_audit_items.select{ |item| item.product_title == product[0] }.each do |variant| %>
                <%= audit.fields_for :stock_audit_items, @audit.stock_audit_items.select{|item| item.variant_id == variant.variant_id}.first do |item| %>
                <% even_or_odd_variant = (even_or_odd_variant - 1).abs %>
                  <tr class="variant<%= even_or_odd_variant %><%= even_or_odd_vendor %>">
                    <td><%= variant.title %> <small>(sku: <%= variant.sku %>)</small></td>
                    <td><%= variant.shopify_count %></td>
                    <td><%= variant.pending_count %></td>
                    <td class="expected"><%= variant.expected_count %></td>
                    <td class="actual"><%= item.text_field :actual_count, :size => 4, :onchange => "calculate_difference(this)" %></td>
                    <td class="difference">0</td>
                  </tr>
                  <%= item.hidden_field :product_id, :value => variant.product_id %>
                  <%= item.hidden_field :variant_id, :value => variant.variant_id %>
                  <%= item.hidden_field :title, :value => variant.title %>
                  <%= item.hidden_field :sku, :value => variant.sku %>
                  <%= item.hidden_field :expected_count, :value => variant.expected_count %>
                  <%= item.hidden_field :vendor, :value => variant.vendor %>
                  <%= item.hidden_field :shopify_count, :value => variant.shopify_count %>
                  <%= item.hidden_field :product_title, :value => variant.product_title %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
        </tbody>
    </table>
    Enter your name: <%= audit.text_field :created_by %>
    <%= audit.hidden_field :shopify_store_id, :value => (current_shop.nil? ? 0 : current_shop.id) %>
    <%= submit_tag 'Complete Audit' %>
  <% end %>

app/views/stock_audits/show.html.erb
<h1 class="blue">Stock Audit</h1>
<small><%= link_to 'Back', stock_audits_path %></small>
<div>Created by <%= @audit.created_by %> on <%= @audit.created_at %><br/></div>
<table>
  <thead>
    <tr>
      <td>Variant</td>
      <td>Expected On Hand</td>
      <td>Actual Count</td>
      <td>Difference</td>
    </tr>
  </thead>
  <tbody>
      <% even_or_odd_vendor = 1 %>
      <% @vendors.each do |vendor| %>
        <% even_or_odd_vendor = (even_or_odd_vendor - 1).abs %>
          <% @products[vendor].each do |product| %>
            <tr>
              <td colspan="6" class="vendor<%= even_or_odd_vendor %>">
                <%= link_to product[0], "http://#{current_shop.domain}/admin/products/#{product[1]}" %> (<%= vendor %>)
              </td>
            </tr>
            <% even_or_odd_variant = 1 %>
            <% @audit.stock_audit_items.select{ |item| item.product_title == product[0] }.each do |variant| %>
            <% even_or_odd_variant = (even_or_odd_variant - 1).abs %>
                <tr class="variant<%= even_or_odd_variant %><%= even_or_odd_vendor %>">
                  <td><%= variant.title %> <small>(sku: <%= variant.sku %>)</small></td>
                  <td class="expected"><%= variant.expected_count %></td>
                  <td class="actual"><%= variant.actual_count %></td>
                  <td class="difference"><%= variant.actual_count - variant.expected_count %></td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
      </tbody>
  </table>